# Site Settings
title: Karmakonsulten Anette Kishori
description: Integrerat Själsarbete med Anette Kishori. Medial vägledning, Vedisk astrologi och samtalsstöd i Gnesta.

# URL Settings 1 - Development: GitHub Pages subpath
#url: "https://penguindoudou.github.io"
#baseurl: "/kishori"

# URL Settings 2 - Development: Workers
#url: "https://kishori.simonsaysautomate.workers.dev"
#baseurl: ""


# URL Settings 3 - Production: Custom Domain
url: "https://kishori.se"
baseurl: ""

# Jekyll settings
timezone: Europe/Stockholm
encoding: utf-8
markdown: kramdown
exclude:
  - .gemini
  - brain
  - task.md
  - implementation_plan.md
  - walkthrough.md
